variables:
  APP_ID: ${APP_ID:-org.vim.Vim}
  BRANCH: ${BRANCH:-stable}
  REF: ${REF:-master}
  BUILD_URL: ${BUILD_URL:-"0"}
  REPO_TOKEN: ${REPO_TOKEN:-foo}

.build:
  image: ghcr.io/flathub-infra/flatpak-builder-lint:unprivileged
  variables:
    REPO: https://github.com/flathub/${APP_ID}
  entrypoint: [""]
  script:
    - curl https://raw.githubusercontent.com/barthalion/justpak/refs/heads/main/justfile -o justfile
    - just checkout $REPO $REF
    - just validate-manifest $APP_ID
    - just prepare-env
    - just build $APP_ID $BRANCH
    - just commit-screenshots
    - just validate-build
    - just generate-deltas
    - just upload $BUILD_URL

build-x86_64:
  extends: .build
  tags:
    - flathub
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "api"