name: Build flatpak

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'Application ID'
        required: true
      branch:
        description: 'Build branch (stable/beta/test)'
        required: true
        default: 'stable'
      repo:
        description: 'Repository URL'
        required: true
      ref:
        description: 'git ref'
        required: true
      build_url:
        description: 'flat-manager build URL'
        required: true
  repository_dispatch:
    types: [build-flatpak]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-builder-lint:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Set variables from dispatch event
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "APP_ID=${{ github.event.client_payload.app_id }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV
          echo "REPO=${{ github.event.client_payload.repo }}" >> $GITHUB_ENV
          echo "REF=${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
          echo "BUILD_URL=${{ github.event.client_payload.build_url }}" >> $GITHUB_ENV

      - name: Set variables from manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "APP_ID=${{ github.event.inputs.app_id }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          echo "REPO=${{ github.event.inputs.repo }}" >> $GITHUB_ENV
          echo "REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
          echo "BUILD_URL=${{ github.event.inputs.build_url }}" >> $GITHUB_ENV

      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Checkout repository
        run: just checkout $REPO $REF

      - name: Prepare environment
        run: just prepare-env

      - name: Validate manifest
        run: just validate-manifest $APP_ID

      - name: Build Flatpak
        run: just build $APP_ID $BRANCH

      - name: Commit screenshots
        run: just commit-screenshots

      - name: Validate build
        run: just validate-build

      - name: Generate deltas
        run: just generate-deltas

      - name: Upload build
        run: just upload $BUILD_URL
