name: Build flatpak
run-name: >-
  Build ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.app_id || github.event.inputs.app_id }}


on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'Application ID'
        required: true
        default: org.vim.Vim
      branch:
        description: 'Build branch (stable/beta/test)'
        required: true
        default: stable
      ref:
        description: 'Git reference'
        required: true
        default: master
      build_url:
        description: 'Build ID'
        required: true
        default: "0"
      runners:
        description: 'JSON array of runners (e.g. ["ubuntu-24.04","ubuntu-24.04-arm"])'
        required: true
        default: '["ubuntu-24.04"]'
      repo_token:
        description: 'Repository token'
        required: true
        default: foo
  repository_dispatch:
    types: [build-flatpak]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        runner: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.runners || fromJSON(github.event.inputs.runners) }}
    name: Build flatpak (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}

    container:
      image: ghcr.io/flathub-infra/flatpak-builder-lint:latest
      options: --privileged

    steps:
      - name: Set variables from dispatch event
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "APP_ID=${{ github.event.client_payload.app_id }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV
          echo "REPO=https://github.com/flathub/${{ github.event.client_payload.app_id }}" >> $GITHUB_ENV
          echo "REF=${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
          echo "BUILD_URL=https://hub.flathub.org/api/v1/build/${{ github.event.client_payload.build_url }}" >> $GITHUB_ENV
          echo "::add-mask::${{ github.event.client_payload.repo_token }}"

      - name: Set variables from manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "APP_ID=${{ github.event.inputs.app_id }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          echo "REPO=https://github.com/flathub/${{ github.event.inputs.app_id }}" >> $GITHUB_ENV
          echo "REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
          echo "BUILD_URL=https://hub.flathub.org/api/v1/build/${{ github.event.inputs.build_url }}" >> $GITHUB_ENV
          echo "::add-mask::${{ github.event.inputs.repo_token }}"

      - name: Fetch justfile
        run: |
          curl https://raw.githubusercontent.com/barthalion/justpak/refs/heads/main/justfile -o justfile

      - name: Checkout repository
        run: |
          git config --global --add safe.directory /__w/justpak/justpak
          just checkout $REPO $REF

      - name: Prepare environment
        run: just prepare-env

      - name: Validate manifest
        run: just validate-manifest $APP_ID

      - name: Build flatpak
        run: just build $APP_ID $BRANCH

      - name: Commit screenshots
        run: just commit-screenshots

      - name: Validate build
        run: just validate-build

      - name: Generate deltas
        run: just generate-deltas

      - name: Upload build
        env:
          REPO_TOKEN: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.repo_token || github.event.inputs.repo_token }}
        run: just upload $BUILD_URL
